/** Autogenerated Main.cpp. */

// =================================| Include only the DSP files  |=================================

#include <AppConfig.h>
#include <hi_dsp_library/hi_dsp_library.h>
#include <hi_faust/hi_faust.h>
#include "includes.h"
// ===========================| Now we can add the rest of the codebase |===========================

#include <JuceHeader.h>

#if !JUCE_WINDOWS
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreturn-type-c-linkage"
#endif

// =======================================| Project Factory |=======================================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations ---------------------------------------------------------------------
		
		registerPolyNode<project::pitch<1>, scriptnode::wrap::illegal_poly<project::pitch<1>>>();
		registerPolyNode<project::klp2<1>, scriptnode::wrap::illegal_poly<project::klp2<1>>>();
		registerPolyNode<project::klp<1>, scriptnode::wrap::illegal_poly<project::klp<1>>>();
		registerPolyNode<project::kk<1>, scriptnode::wrap::illegal_poly<project::kk<1>>>();
		registerPolyNode<project::khp2<1>, scriptnode::wrap::illegal_poly<project::khp2<1>>>();
		registerPolyNode<project::khp<1>, scriptnode::wrap::illegal_poly<project::khp<1>>>();
		registerPolyNode<project::Folder<1>, scriptnode::wrap::illegal_poly<project::Folder<1>>>();
		registerPolyNode<project::Comb<1>, scriptnode::wrap::illegal_poly<project::Comb<1>>>();
		registerPolyNode<project::Arrange<1>, wrap::illegal_poly<project::Arrange<1>>>();
		registerPolyNode<project::Comp<1>, wrap::illegal_poly<project::Comp<1>>>();
		registerPolyNode<project::FileShape<1>, wrap::illegal_poly<project::FileShape<1>>>();
		registerPolyNode<project::Mod1<1>, wrap::illegal_poly<project::Mod1<1>>>();
		registerPolyNode<project::Modifier<1>, wrap::illegal_poly<project::Modifier<1>>>();
		registerPolyNode<project::MultiFilter<1>, wrap::illegal_poly<project::MultiFilter<1>>>();
		registerPolyNode<project::PostFilter<1>, wrap::illegal_poly<project::PostFilter<1>>>();
		registerDataNode<project::Clip_networkdata>();
		registerDataNode<project::Conv_networkdata>();
		registerDataNode<project::Follow1_networkdata>();
		registerDataNode<project::InputRoute_networkdata>();
		registerDataNode<project::io2_networkdata>();
		registerDataNode<project::io3_networkdata>();
		registerDataNode<project::io4_networkdata>();
		registerDataNode<project::io5_networkdata>();
		registerDataNode<project::io6_networkdata>();
		registerDataNode<project::ModConnections_networkdata>();
		registerDataNode<project::PostTrack_networkdata>();
		registerDataNode<project::Pshift_networkdata>();
		registerDataNode<project::rout_networkdata>();
		registerDataNode<project::Routing_networkdata>();
	}
};
}

scriptnode::dll::FactoryBase* scriptnode::DspNetwork::createStaticFactory()
{
	return new project::Factory();
}

#if !JUCE_WINDOWS
#pragma clang diagnostic pop
#endif


