/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include third party header files ----------------

#include "Comb.h"
#include "Folder.h"
#include "khp.h"
#include "khp2.h"
#include "kk.h"
#include "klp.h"
#include "klp2.h"
#include "pitch.h"

// Include compiled network files ------------------

#include "Arrange.h"
#include "Clip_networkdata.h"
#include "Comp.h"
#include "Conv_networkdata.h"
#include "FileShape.h"
#include "Follow1_networkdata.h"
#include "InputRoute_networkdata.h"
#include "io2_networkdata.h"
#include "io3_networkdata.h"
#include "io4_networkdata.h"
#include "io5_networkdata.h"
#include "io6_networkdata.h"
#include "Mod1.h"
#include "ModConnections_networkdata.h"
#include "Modifier.h"
#include "MultiFilter.h"
#include "PostFilter.h"
#include "PostTrack_networkdata.h"
#include "Pshift_networkdata.h"
#include "Routing_networkdata.h"
#include "rout_networkdata.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

