#!/bin/bash
PATH="/usr/local/bin:$PATH"
chmod +x "/Users/rick/Documents/HISE OLD/HISE-a20873ea7a8c00b251ddae7df8d6e3007f8c5f71/tools/Projucer/Projucer.app/Contents/MacOS/Projucer"
cd "`dirname "$0"`"
"/Users/rick/Documents/HISE OLD/HISE-a20873ea7a8c00b251ddae7df8d6e3007f8c5f71/tools/Projucer/Projucer.app/Contents/MacOS/Projucer" --resave AutogeneratedProject.jucer

set -o pipefail
echo Compiling   OneWayTicket ...
xcodebuild -project "Builds/MacOSX/ OneWayTicket.xcodeproj" -configuration "Release" -jobs "10" | "/Users/rick/Documents/HISE OLD/HISE-a20873ea7a8c00b251ddae7df8d6e3007f8c5f71/tools/Projucer/xcbeautify"
