/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include third party header files ----------------

#include "Comb.h"
#include "Folder.h"
#include "khp.h"
#include "khp2.h"
#include "kk.h"
#include "klp.h"
#include "klp2.h"
#include "pitch.h"

// Include compiled network files ------------------

#include "Arrange.h"
#include "Comp.h"
#include "FileShape.h"
#include "Mod1.h"
#include "Modifier.h"
#include "MultiFilter.h"
#include "PostFilter.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

