/** Autogenerated Main.cpp. */

// =================================| Include only the DSP files  |=================================

#include <AppConfig.h>
#include <hi_dsp_library/hi_dsp_library.h>
#include <hi_faust/hi_faust.h>
#include "includes.h"
// ===========================| Now we can add the rest of the codebase |===========================

#include <JuceHeader.h>

#if !JUCE_WINDOWS
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreturn-type-c-linkage"
#endif

// =======================================| Project Factory |=======================================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations ---------------------------------------------------------------------
		
		registerPolyNode<project::pitch<1>, scriptnode::wrap::illegal_poly<project::pitch<1>>>();
		registerPolyNode<project::klp2<1>, scriptnode::wrap::illegal_poly<project::klp2<1>>>();
		registerPolyNode<project::klp<1>, scriptnode::wrap::illegal_poly<project::klp<1>>>();
		registerPolyNode<project::kk<1>, scriptnode::wrap::illegal_poly<project::kk<1>>>();
		registerPolyNode<project::khp2<1>, scriptnode::wrap::illegal_poly<project::khp2<1>>>();
		registerPolyNode<project::khp<1>, scriptnode::wrap::illegal_poly<project::khp<1>>>();
		registerPolyNode<project::Folder<1>, scriptnode::wrap::illegal_poly<project::Folder<1>>>();
		registerPolyNode<project::Comb<1>, scriptnode::wrap::illegal_poly<project::Comb<1>>>();
		registerPolyNode<project::Arrange<1>, wrap::illegal_poly<project::Arrange<1>>>();
		registerPolyNode<project::Comp<1>, wrap::illegal_poly<project::Comp<1>>>();
		registerPolyNode<project::FileShape<1>, wrap::illegal_poly<project::FileShape<1>>>();
		registerPolyNode<project::Mod1<1>, wrap::illegal_poly<project::Mod1<1>>>();
		registerPolyNode<project::Modifier<1>, wrap::illegal_poly<project::Modifier<1>>>();
		registerPolyNode<project::MultiFilter<1>, wrap::illegal_poly<project::MultiFilter<1>>>();
		registerPolyNode<project::PostFilter<1>, wrap::illegal_poly<project::PostFilter<1>>>();
	}
};
}

project::Factory f;

// ===================================| Exported DLL functions |===================================

DLL_EXPORT int getNumNodes()
{
	return f.getNumNodes();
}

DLL_EXPORT size_t getNodeId(int index, char* t)
{
	return HelperFunctions::writeString(t, f.getId(index).getCharPointer());
}

DLL_EXPORT bool isThirdPartyNode(int index)
{
	return index < 8;
}

DLL_EXPORT int getNumDataObjects(int nodeIndex, int dataTypeAsInt)
{
	return f.getNumDataObjects(nodeIndex, dataTypeAsInt);
}

DLL_EXPORT void deInitOpaqueNode(scriptnode::OpaqueNode* n)
{
	n->callDestructor();
}

DLL_EXPORT void initOpaqueNode(scriptnode::OpaqueNode* n, int index, bool polyIfPossible)
{
	f.initOpaqueNode(n, index, polyIfPossible);
}
DLL_EXPORT int getHash(int index)
{
	static const int thirdPartyOffset = 8;
	static const int hashIndexes[7] =
	{
		-552436998,
		1226461275,
		1461552404,
		-1757519686,
		1175797001,
		1963460856,
		-935090147
	};
	return (index >= thirdPartyOffset) ? hashIndexes[index - thirdPartyOffset] : 0;
}
DLL_EXPORT int getWrapperType(int index)
{
	return f.getWrapperType(index);
}
DLL_EXPORT ErrorC getError()
{
	return f.getError();
}
DLL_EXPORT void clearError()
{
	f.clearError();
}
DLL_EXPORT int getDllVersionCounter()
{
	return scriptnode::dll::ProjectDll::DllUpdateCounter;
}

#if !JUCE_WINDOWS
#pragma clang diagnostic pop
#endif


